/* Auto-generated by scripts/download-btd6-heroes.ts — do not edit by hand */
export type HeroCosts = {
  easy: number | null;
  medium: number;
  hard: number | null;
  impoppable: number | null;
};

export type HeroPortraitStage = 1 | 3 | 7 | 10 | 20;

export type HeroPortraits = Record<"1" | "3" | "7" | "10" | "20", string>;

export type HeroEntity = {
  id: string;
  name: string;
  title: string;
  description: string;
  costs: HeroCosts;
  cost: number;
  image: string;
  sourceFile: string;
  portraits: HeroPortraits;
  unlock: string;
  levelSpeed: number;
  isAltForm?: boolean;
  baseHeroId?: string;
};

import data from "./heroes.json";

export const heroEntities = data as HeroEntity[];

/** Base roster (excludes alt forms like Masqued Macaque). */
export const heroes = heroEntities.filter((h) => !h.isAltForm);

/** Portrait path for an in-game hero level (1–20). */
export function heroPortraitForLevel(
  hero: HeroEntity,
  level: number,
): string {
  const n = Math.max(1, Math.min(20, Math.floor(level) || 1));
  if (n >= 20) return hero.portraits["20"] ?? hero.image;
  if (n >= 10) return hero.portraits["10"] ?? hero.image;
  if (n >= 7) return hero.portraits["7"] ?? hero.image;
  if (n >= 3) return hero.portraits["3"] ?? hero.image;
  return hero.portraits["1"] ?? hero.image;
}

export function heroById(id: string): HeroEntity | null {
  return heroEntities.find((h) => h.id === id) ?? null;
}
