/* Auto-generated by scripts/download-btd6-maps.ts - do not edit by hand */
import type { MapEntity } from "./types";
import data from "./maps.json";

export const maps = data as MapEntity[];

export const mapsByDifficulty = maps.reduce<Record<string, MapEntity[]>>(
  (acc, m) => {
    (acc[m.difficulty] ??= []).push(m);
    return acc;
  },
  {},
);

export function findMap(id: string): MapEntity | undefined {
  return maps.find((m) => m.id === id);
}
