/* Auto-generated by scripts/download-btd6-assets.ts — do not edit by hand */
import type { TowerEntity } from "./types";
import data from "./towers.json";

export const towerEntities = data as TowerEntity[];

export const towers = towerEntities.filter((e) => e.type === "tower");
export const upgrades = towerEntities.filter((e) => e.type === "upgrade" || e.type === "paragon");
export const byTower = towerEntities.reduce<Record<string, TowerEntity[]>>((acc, e) => {
  (acc[e.tower] ??= []).push(e);
  return acc;
}, {});
